# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rQsoM2uxXxrlyo81_iME-fDZIpjj986P
"""

import numpy as np

y = np.array([92.85,103,96,102,101,10.3,108,123,203,280,307,263])
x= np.array([1,2,3,4,5,6,7,8,9,10,11,12])

x_dash=np.mean(x)

y_dash=np.mean(y)

p= (x-x_dash)*(y-y_dash)

n = np.size(x)

x_mean = np.mean(x)
y_mean = np.mean(y)
x_mean,y_mean

Q = (x-x_dash)*(x-x_dash)

den = sum(Q)

x_dash

P = (x-x_dash) * (y-y_dash)

num = sum(P)

num

Q = (x-x_dash)*(x-x_dash)

den = sum(Q)

m= num/den

m

c=y_dash - m* x_dash

Ynew=m*x + c

Ynew

import matplotlib.pyplot as plt

plt.scatter(x,y)

plt.scatter(x,y)
plt.plot(x,Ynew)

y=m*7+c
y

